//! `hort-cli attribution` — print the generated third-party attribution
//! document embedded in the binary.
//!
//! Synchronous, no config, no server call — mirrors `completions` /
//! `license`. The document itself is generated by `cargo about` from
//! the dependency graph and committed at the repository root; see the
//! `hort-attribution` crate docs for the regeneration procedure.

use std::process::ExitCode;

use hort_attribution::AttributionFormat;

/// Output format for `hort-cli attribution`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum AttributionFormatArg {
    /// Human-readable Markdown (default).
    Text,
    /// Machine-readable JSON array.
    Json,
}

impl From<AttributionFormatArg> for AttributionFormat {
    fn from(value: AttributionFormatArg) -> Self {
        match value {
            AttributionFormatArg::Text => AttributionFormat::Text,
            AttributionFormatArg::Json => AttributionFormat::Json,
        }
    }
}

/// `attribution` arguments.
#[derive(clap::Args, Debug)]
pub struct AttributionArgs {
    /// Output format.
    #[arg(long, value_enum, default_value_t = AttributionFormatArg::Text)]
    pub format: AttributionFormatArg,
}

/// Print the embedded third-party attribution document to stdout and
/// exit 0. A closed stdout pipe (`| head`) exits cleanly rather than
/// panicking — see `hort_attribution::write_stdout_or_exit`.
pub fn run(args: &AttributionArgs) -> ExitCode {
    hort_attribution::write_stdout_or_exit(hort_attribution::render_attribution(args.format.into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_format_is_default_and_succeeds() {
        let code = run(&AttributionArgs {
            format: AttributionFormatArg::Text,
        });
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }

    #[test]
    fn json_format_differs_from_text_and_succeeds() {
        let text = hort_attribution::render_attribution(AttributionFormat::Text);
        let json = hort_attribution::render_attribution(AttributionFormat::Json);
        assert_ne!(text, json);
        let code = run(&AttributionArgs {
            format: AttributionFormatArg::Json,
        });
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }

    #[test]
    fn attribution_args_parses_via_cli_default_text() {
        use clap::Parser;

        let cli = crate::Cli::try_parse_from(["hort-cli", "attribution"]).unwrap();
        let Some(crate::Commands::Attribution(args)) = cli.cmd else {
            panic!("expected Commands::Attribution");
        };
        assert_eq!(args.format, AttributionFormatArg::Text);

        let cli =
            crate::Cli::try_parse_from(["hort-cli", "attribution", "--format", "json"]).unwrap();
        let Some(crate::Commands::Attribution(args)) = cli.cmd else {
            panic!("expected Commands::Attribution");
        };
        assert_eq!(args.format, AttributionFormatArg::Json);
    }
}
