-- Migration 019 — `content_first_seen`: the content-level age projection.
--
-- Implements the primary evidence source of
-- `docs/adr/0054-content-level-age-evidence-anchors-quarantine.md`:
-- per SHA-256 content hash, the **minimum** over hort's own ingest
-- observations across every repository of this instance.
--
-- Domain port:    crates/hort-domain/src/ports/content_first_seen.rs
-- Postgres adapter: crates/hort-adapters-postgres/src/content_first_seen.rs
--
-- ## Why a content-level table and not a column on `artifacts`
--
-- `artifacts` is per-repository: one CAS entry carries one row per
-- repository that holds it. ADR 0054 requires the age fact to survive
-- deletion of individual per-repo rows, and to be identical for the same
-- bytes in every repository — neither holds for a per-row column. A row
-- here is keyed by the content hash alone and is owned by no repository.
--
-- ## Deliberately NO foreign key to `artifacts`
--
-- An FK (with any ON DELETE action) would tie the record's lifetime to
-- the per-repo rows it must outlive. Retention purge deletes per-repo
-- rows and the storage GC deletes the CAS blob once the last reference
-- is gone; the observation "hort held these bytes at time T" remains
-- true afterwards, and re-ingesting the same content later must recover
-- the ORIGINAL first-seen instant rather than restarting the clock. So
-- the table is intentionally free-standing: nothing cascades into it,
-- and no code path deletes from it.
--
-- Consequence, accepted deliberately: the table grows by one row per
-- distinct content hash the instance has ever ingested and is never
-- pruned. A row is ~80 bytes; a registry holding a million distinct
-- blobs pays well under 100 MB. Pruning it would be indistinguishable
-- from the cascade this table exists to avoid.
--
-- ## The `min` is enforced here, in SQL
--
-- The adapter's write is
--   INSERT … ON CONFLICT (content_hash) DO UPDATE
--     SET first_seen_at = LEAST(content_first_seen.first_seen_at,
--                               EXCLUDED.first_seen_at)
--     WHERE content_first_seen.first_seen_at > EXCLUDED.first_seen_at
-- so the minimum is computed against the locked, latest committed row
-- inside one statement. A read-modify-write in application code would
-- lose exactly the race this projection must survive: concurrent
-- ingests of the same content across different repositories are the
-- normal case, not an edge case. The `WHERE` guard makes the common
-- path (a later observation of already-seen content) a no-op that
-- writes no new row version.
--
-- ## One-time seed from the history the instance still holds
--
-- The `INSERT … SELECT` below is not a convenience: it is the only
-- chance to recover history that is already decaying. Every live
-- `artifacts` row carries `created_at` — the instant hort minted that
-- row, i.e. an observation that hort held those bytes at that time —
-- and `min(created_at)` per checksum over all repositories is exactly
-- the value this table's write path would have produced had it existed
-- from the start. Without the seed, content ingested before this
-- migration first anchors at its NEXT registration, so the instances
-- with the most history (months of artifacts) would get the least
-- benefit from a projection whose entire premise is that hort already
-- knows how old this content is.
--
-- It is genuinely one-time. Retention purge deletes per-repo rows and
-- takes each row's `created_at` with it, so the evidence available to
-- this statement only shrinks: a later migration attempting the same
-- recovery would recover strictly less.
--
-- Soft-deleted rows (`is_deleted = true`) are INCLUDED deliberately.
-- The fact being recovered is "hort held these bytes at time T", which
-- a later soft delete does not undo; excluding them could only move the
-- recovered instant later, which is the outcome the seed exists to
-- avoid.
--
-- `ON CONFLICT DO NOTHING` makes the statement safe in both directions:
-- on a fresh install there is nothing to select and it is a no-op, and
-- were it ever replayed against a populated table it would leave every
-- existing record alone rather than overwrite a value the write path
-- has since lowered. It cannot lose a minimum on its own: `GROUP BY`
-- makes the source key-unique, so no row in this statement can conflict
-- with another row of the same statement.
--
-- ## Why the seed filters on hash shape instead of trusting the source
--
-- `artifacts.checksum_sha256` is `character(64)` and carries NO CHECK
-- constraint (`migrations/003_artifacts_cas.sql`). Today's write path
-- can only put a canonical value there — it goes through
-- `hort_domain::types::ContentHash`, which admits nothing but 64
-- lowercase hex characters — and a `sha256:`-prefixed value cannot even
-- be stored (71 characters do not fit `character(64)`), so the column
-- holds bare digests. But 003 is a squashed baseline over a prototype
-- history that had no such guarantee, and `character(64)` blank-pads a
-- short value rather than rejecting it (the pad is then trimmed by the
-- cast to `text`, yielding a value the shape CHECK below rejects).
--
-- So the seed is written fail-open on the row and fail-closed on the
-- table: a row whose stored checksum does not match the canonical shape
-- is SKIPPED, never inserted. The alternative — letting the shape CHECK
-- abort the statement — would make this migration fail, and a failed
-- migration means the deployment does not boot. Losing one legacy row's
-- age evidence is a bounded, conservative loss (that content re-anchors
-- at its next registration, exactly as it would have without any seed);
-- refusing to start is not.
--
-- ## Shape CHECK
--
-- `hort_domain::types::ContentHash` already guarantees 64 lowercase hex
-- characters, so the CHECK is defence-in-depth against an out-of-band
-- writer. It matters more here than on other hash columns: the hash IS
-- the primary key, so a differently-cased or padded value would create a
-- SECOND record for the same bytes and silently lose the minimum the
-- table exists to hold.
--
-- `text` (not `character(64)`) follows the newer `content_references.
-- target_content_hash` choice — no blank-padding to trim at the
-- adapter boundary.
--
-- ## Indexes
--
-- None beyond the primary key. The only access pattern is an equality
-- lookup / upsert by content hash, which the PK's unique index serves.
--
-- GRANTs / role wiring: none. Per the post-004 convention (ADR 0009)
-- operators run the role-bootstrap recipe before applying migrations and
-- `ALTER DEFAULT PRIVILEGES` auto-grants SELECT/INSERT/UPDATE/DELETE on
-- future tables created by `hort_admin`.
--
-- Reversal: sqlx::migrate! is UP-only; the project maintains no paired
-- *.down.sql. Manual reversal, if ever needed, drops the table — note
-- that doing so is irrecoverable (see the structural guard below) and
-- that the migration must never be edited in place once applied (the
-- checksum `sqlx::migrate!` validates would reject every migrated
-- database's boot).
--
-- Structural guard: `content_first_seen` is on the maintained sensitive
-- table list of `crates/hort-app/tests/no_sensitive_drops.rs`. Unlike
-- `content_references` — which the refcount-reconcile sweep rebuilds
-- from the authoritative `artifacts` rows — this projection has NO
-- authoritative source to rebuild from: the observations are the only
-- record that they happened. Losing it hands the quarantine anchor back
-- to the attacker-assertable upstream publish time that ADR 0054's
-- primary source exists to displace.
--
-- Idempotence: this migration runs exactly once via the
-- `_sqlx_migrations` ledger. CREATE TABLE carries NO `IF NOT EXISTS`
-- guard — a pre-existing `content_first_seen` means the database has
-- diverged from this chain and the migration must fail loudly rather
-- than adopt a table of unknown provenance as the age record. The seed
-- that follows it is nonetheless written to be re-runnable in principle
-- (`ON CONFLICT DO NOTHING`), so it never becomes the reason a repair
-- cannot replay this file's data step.

CREATE TABLE public.content_first_seen (
    content_hash text PRIMARY KEY,
    first_seen_at timestamp with time zone NOT NULL,
    CONSTRAINT content_first_seen_hash_shape_check
        CHECK (content_hash ~ '^[0-9a-f]{64}$')
);

-- Seed the projection from the observations the instance still holds.
-- See "One-time seed from the history the instance still holds" above
-- for why this runs here and why non-canonical rows are skipped rather
-- than allowed to abort the migration. The explicit `::text` casts make
-- the `character(64)` → `text` conversion (which trims the blank pad)
-- happen once, visibly, in all three positions.
INSERT INTO public.content_first_seen (content_hash, first_seen_at)
SELECT a.checksum_sha256::text, MIN(a.created_at)
  FROM public.artifacts a
 WHERE a.checksum_sha256::text ~ '^[0-9a-f]{64}$'
 GROUP BY a.checksum_sha256::text
ON CONFLICT (content_hash) DO NOTHING;
