{{- if or (gt (int .Values.replicaCount) 1) .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hort-server.fullname" . }}
  labels:
    {{- include "hort-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "hort-server.selectorLabels" . | nindent 6 }}
{{- end -}}
