//! hort's license identifier, license texts, and generated third-party
//! attribution — embedded at compile time via `include_str!` of files
//! committed at the repository root, and shared by the `license` /
//! `attribution` subcommands on all three shipped binaries (`hort-server`,
//! `hort-worker`, `hort-cli`).
//!
//! This is a std-only leaf crate with **zero `hort-*` dependencies** — see
//! the crate's `Cargo.toml` for why that isolation matters. All logic here
//! is pure (no I/O, no env reads); each binary's clap wiring is a thin
//! dispatch shim on top of [`render_license`] / [`render_attribution`].
//!
//! # Regenerating the embedded third-party document
//!
//! `THIRD_PARTY_MD` / `THIRD_PARTY_JSON` are generated by `cargo about` from
//! the dependency graph, not hand-written. Run
//! `scripts/regenerate-attribution.sh` and commit the result after any
//! change that could alter the graph; see `about.toml` and the templates
//! under `about/`.

use std::io::{self, Write};
use std::process::ExitCode;

/// hort's SPDX license expression.
pub const SPDX: &str = "MIT OR Apache-2.0";

/// Full text of the MIT license (`LICENSE-MIT` at the repository root).
pub const LICENSE_MIT: &str = include_str!("../../../LICENSE-MIT");

/// Full text of the Apache License 2.0 (`LICENSE-APACHE` at the repository
/// root).
pub const LICENSE_APACHE: &str = include_str!("../../../LICENSE-APACHE");

/// Generated third-party attribution, human-readable Markdown form
/// (`THIRD-PARTY-LICENSES.md` at the repository root). See
/// [`render_attribution`].
const THIRD_PARTY_MD: &str = include_str!("../../../THIRD-PARTY-LICENSES.md");

/// Generated third-party attribution, machine-readable JSON form
/// (`THIRD-PARTY-LICENSES.json` at the repository root). See
/// [`render_attribution`].
const THIRD_PARTY_JSON: &str = include_str!("../../../THIRD-PARTY-LICENSES.json");

/// Renders the `license` subcommand's output.
///
/// Non-`full`: the SPDX expression plus a pointer to the two license files.
/// `full`: also appends the complete text of both `LICENSE-MIT` and
/// `LICENSE-APACHE`, each under its own labelled section.
pub fn render_license(full: bool) -> String {
    let mut out = format!(
        "hort is dual-licensed under {SPDX}.\n\n\
         See LICENSE-MIT and LICENSE-APACHE in the repository root for the full license texts.\n"
    );

    if full {
        out.push_str("\n=== LICENSE-MIT ===\n\n");
        out.push_str(LICENSE_MIT);
        out.push_str("\n=== LICENSE-APACHE ===\n\n");
        out.push_str(LICENSE_APACHE);
    }

    out
}

/// Output format for the `attribution` subcommand.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttributionFormat {
    /// Human-readable Markdown (`THIRD-PARTY-LICENSES.md`).
    Text,
    /// Machine-readable JSON array of `{name, version, url, spdx,
    /// license_text}` (`THIRD-PARTY-LICENSES.json`).
    Json,
}

/// Renders the `attribution` subcommand's output: the embedded third-party
/// attribution document in the requested format, verbatim.
pub fn render_attribution(format: AttributionFormat) -> &'static str {
    match format {
        AttributionFormat::Text => THIRD_PARTY_MD,
        AttributionFormat::Json => THIRD_PARTY_JSON,
    }
}

/// Write `s` to stdout, exiting cleanly instead of panicking if the reader
/// has gone away.
///
/// Rust ignores `SIGPIPE` by default and never resets it (that would need
/// `libc::signal`, `unsafe`, forbidden workspace-wide), so writing to a pipe
/// whose consumer already exited (`| head`, `| less` then `q`) surfaces as
/// an `io::Error` rather than killing the process via signal. `print!` /
/// `println!` unwrap that error and panic ("failed printing to stdout").
/// This helper is the shared fix for every print-and-exit subcommand: the
/// consumer already got all the bytes it wanted, so a `BrokenPipe` write
/// error is swallowed into a clean `ExitCode::SUCCESS`. Any other write
/// error still panics, same as `print!` today.
pub fn write_stdout_or_exit(s: &str) -> ExitCode {
    write_to_or_exit(&mut io::stdout(), s)
}

/// Generic-sink form of [`write_stdout_or_exit`]: same BrokenPipe-to-clean-exit
/// behaviour, against any [`Write`] rather than a hardcoded `io::stdout()`.
/// Every `run()` in the CLI/server/worker binaries funnels through this so
/// their tests can assert on an in-memory sink's bytes instead of writing an
/// unbounded document to the real stdout every test run.
pub fn write_to_or_exit<W: Write>(w: &mut W, s: &str) -> ExitCode {
    match w.write_all(s.as_bytes()).and_then(|()| w.flush()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) if e.kind() == io::ErrorKind::BrokenPipe => ExitCode::SUCCESS,
        Err(e) => panic!("failed printing to stdout: {e}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spdx_is_dual_mit_apache() {
        assert_eq!(SPDX, "MIT OR Apache-2.0");
    }

    #[test]
    fn render_license_short_names_spdx_and_points_at_files() {
        let out = render_license(false);
        assert!(out.contains("MIT OR Apache-2.0"));
        assert!(out.contains("LICENSE-MIT"));
        assert!(out.contains("LICENSE-APACHE"));
        // Non-full must not inline the full texts.
        assert!(!out.contains("Permission is hereby granted"));
        assert!(!out.contains("TERMS AND CONDITIONS FOR USE"));
    }

    #[test]
    fn render_license_full_inlines_both_license_texts() {
        let out = render_license(true);
        assert!(out.contains("MIT OR Apache-2.0"));
        // Landmark strings from each license's canonical text.
        assert!(out.contains("Permission is hereby granted"));
        assert!(out.contains("Apache License"));
        assert!(out.contains("TERMS AND CONDITIONS FOR USE"));
    }

    #[test]
    fn license_consts_hold_the_expected_license_texts() {
        assert!(LICENSE_MIT.contains("Permission is hereby granted"));
        assert!(LICENSE_APACHE.contains("Apache License"));
    }

    #[test]
    fn render_attribution_text_is_nonempty_markdown() {
        let out = render_attribution(AttributionFormat::Text);
        assert!(!out.is_empty());
        assert!(out.contains("Third-Party Licenses"));
    }

    #[test]
    fn render_attribution_json_is_nonempty_and_differs_from_text() {
        let text = render_attribution(AttributionFormat::Text);
        let json = render_attribution(AttributionFormat::Json);
        assert!(!json.is_empty());
        assert_ne!(text, json);
        assert!(json.trim_start().starts_with('['));
    }

    #[test]
    fn attribution_format_is_debug_clone_copy_eq() {
        let a = AttributionFormat::Text;
        let b = a;
        assert_eq!(a, b);
        assert_ne!(AttributionFormat::Text, AttributionFormat::Json);
        assert_eq!(format!("{a:?}"), "Text");
        assert_eq!(format!("{:?}", AttributionFormat::Json), "Json");
    }

    // Both fixtures accept every `write` call (like a `LineWriter` buffering
    // a trailing partial line) and only fail on the final `flush` — the
    // realistic shape of a `BrokenPipe` surfacing from `io::stdout()`, whose
    // internal `LineWriter` doesn't necessarily hit the OS `write(2)` on
    // every call to `write_all`.
    struct BrokenPipeWriter;

    impl Write for BrokenPipeWriter {
        fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
            Ok(buf.len())
        }

        fn flush(&mut self) -> io::Result<()> {
            Err(io::Error::from(io::ErrorKind::BrokenPipe))
        }
    }

    struct OtherErrorWriter;

    impl Write for OtherErrorWriter {
        fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
            Ok(buf.len())
        }

        fn flush(&mut self) -> io::Result<()> {
            Err(io::Error::from(io::ErrorKind::Other))
        }
    }

    #[test]
    fn write_to_or_exit_writes_full_content_and_succeeds() {
        let mut buf: Vec<u8> = Vec::new();
        let code = write_to_or_exit(&mut buf, "hello, world");
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
        assert_eq!(buf, b"hello, world");
    }

    #[test]
    fn write_to_or_exit_swallows_broken_pipe_into_clean_success() {
        let mut w = BrokenPipeWriter;
        // Must not panic — a `BrokenPipe` write error means the consumer
        // already got all the bytes it wanted (e.g. `| head`), not a
        // failure.
        let code = write_to_or_exit(&mut w, "hello");
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }

    #[test]
    #[should_panic(expected = "failed printing to stdout")]
    fn write_to_or_exit_panics_on_non_broken_pipe_error() {
        let mut w = OtherErrorWriter;
        let _ = write_to_or_exit(&mut w, "hello");
    }

    #[test]
    fn write_stdout_or_exit_writes_to_real_stdout_and_succeeds() {
        // Exercises the public `io::stdout()`-backed entry point itself
        // (every other test above drives the public, injectable
        // `write_to_or_exit` so it can simulate `BrokenPipe`/other errors).
        let code = write_stdout_or_exit("coverage exercise for write_stdout_or_exit\n");
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }
}
