//! `hort-worker attribution` — print the generated third-party
//! attribution document embedded in the binary.
//!
//! Synchronous, no config, no DB, no Tokio runtime — dispatched
//! directly from `main`'s already-synchronous match (see
//! `main::main`). The document is generated by `cargo about` from the
//! dependency graph and committed at the repository root; see the
//! `hort-attribution` crate docs for the regeneration procedure.

use clap::{Args, ValueEnum};

use hort_attribution::AttributionFormat;

/// Output format for `hort-worker attribution`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum AttributionFormatArg {
    /// Human-readable Markdown (default).
    Text,
    /// Machine-readable JSON array.
    Json,
}

impl From<AttributionFormatArg> for AttributionFormat {
    fn from(value: AttributionFormatArg) -> Self {
        match value {
            AttributionFormatArg::Text => AttributionFormat::Text,
            AttributionFormatArg::Json => AttributionFormat::Json,
        }
    }
}

/// Arguments to `hort-worker attribution`.
#[derive(Debug, Args)]
pub struct AttributionArgs {
    /// Output format.
    #[arg(long, value_enum, default_value_t = AttributionFormatArg::Text)]
    pub format: AttributionFormatArg,
}

/// Print the embedded third-party attribution document to stdout. A
/// closed stdout pipe (`| head`) exits cleanly rather than panicking —
/// see `hort_attribution::write_stdout_or_exit`.
pub fn run(args: &AttributionArgs) -> anyhow::Result<()> {
    let _ = run_to(&mut std::io::stdout(), args);
    Ok(())
}

/// Generic-sink form of [`run`]: same rendering and exit behaviour against
/// any [`std::io::Write`], so tests can assert on the written bytes without
/// printing the embedded document to the real stdout.
fn run_to<W: std::io::Write>(w: &mut W, args: &AttributionArgs) -> std::process::ExitCode {
    hort_attribution::write_to_or_exit(w, hort_attribution::render_attribution(args.format.into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_format_is_default_and_succeeds() {
        let mut buf: Vec<u8> = Vec::new();
        let code = run_to(
            &mut buf,
            &AttributionArgs {
                format: AttributionFormatArg::Text,
            },
        );
        assert_eq!(
            format!("{code:?}"),
            format!("{:?}", std::process::ExitCode::SUCCESS)
        );
        assert!(!buf.is_empty());
        let out = String::from_utf8(buf).unwrap();
        assert!(
            out.contains("serde"),
            "expected a known crate name in output"
        );
    }

    #[test]
    fn json_format_differs_from_text_and_succeeds() {
        let text = hort_attribution::render_attribution(AttributionFormat::Text);
        let json = hort_attribution::render_attribution(AttributionFormat::Json);
        assert_ne!(text, json);
        let mut buf: Vec<u8> = Vec::new();
        let code = run_to(
            &mut buf,
            &AttributionArgs {
                format: AttributionFormatArg::Json,
            },
        );
        assert_eq!(
            format!("{code:?}"),
            format!("{:?}", std::process::ExitCode::SUCCESS)
        );
        let parsed: serde_json::Value = serde_json::from_slice(&buf).expect("valid JSON");
        let entries = parsed.as_array().expect("JSON array");
        assert!(!entries.is_empty(), "expected > 0 attribution entries");
    }
}
