//! `hort-worker attribution` — print the generated third-party
//! attribution document embedded in the binary.
//!
//! Synchronous, no config, no DB, no Tokio runtime — dispatched
//! directly from `main`'s already-synchronous match (see
//! `main::main`). The document is generated by `cargo about` from the
//! dependency graph and committed at the repository root; see the
//! `hort-attribution` crate docs for the regeneration procedure.

use clap::{Args, ValueEnum};

use hort_attribution::AttributionFormat;

/// Output format for `hort-worker attribution`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum AttributionFormatArg {
    /// Human-readable Markdown (default).
    Text,
    /// Machine-readable JSON array.
    Json,
}

impl From<AttributionFormatArg> for AttributionFormat {
    fn from(value: AttributionFormatArg) -> Self {
        match value {
            AttributionFormatArg::Text => AttributionFormat::Text,
            AttributionFormatArg::Json => AttributionFormat::Json,
        }
    }
}

/// Arguments to `hort-worker attribution`.
#[derive(Debug, Args)]
pub struct AttributionArgs {
    /// Output format.
    #[arg(long, value_enum, default_value_t = AttributionFormatArg::Text)]
    pub format: AttributionFormatArg,
}

/// Print the embedded third-party attribution document to stdout. A
/// closed stdout pipe (`| head`) exits cleanly rather than panicking —
/// see `hort_attribution::write_stdout_or_exit`.
pub fn run(args: &AttributionArgs) -> anyhow::Result<()> {
    let _ = hort_attribution::write_stdout_or_exit(hort_attribution::render_attribution(
        args.format.into(),
    ));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_format_is_default_and_succeeds() {
        assert!(run(&AttributionArgs {
            format: AttributionFormatArg::Text,
        })
        .is_ok());
    }

    #[test]
    fn json_format_differs_from_text_and_succeeds() {
        let text = hort_attribution::render_attribution(AttributionFormat::Text);
        let json = hort_attribution::render_attribution(AttributionFormat::Json);
        assert_ne!(text, json);
        assert!(run(&AttributionArgs {
            format: AttributionFormatArg::Json,
        })
        .is_ok());
    }
}
