//! `hort-server attribution` — print the generated third-party
//! attribution document embedded in the binary.
//!
//! Synchronous and DSN-free: no `Config::from_env`, no Tokio runtime.
//! The document is generated by `cargo about` from the compiled-in
//! crate graph and committed at the repository root; see the
//! `hort-attribution` crate docs for the regeneration procedure.

use std::process::ExitCode;

use clap::{Args, ValueEnum};

use hort_attribution::AttributionFormat;

/// Output format for `hort-server attribution`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum AttributionFormatArg {
    /// Human-readable Markdown (default).
    Text,
    /// Machine-readable JSON array.
    Json,
}

impl From<AttributionFormatArg> for AttributionFormat {
    fn from(value: AttributionFormatArg) -> Self {
        match value {
            AttributionFormatArg::Text => AttributionFormat::Text,
            AttributionFormatArg::Json => AttributionFormat::Json,
        }
    }
}

/// Arguments to `hort-server attribution`.
#[derive(Debug, Args)]
pub struct AttributionArgs {
    /// Output format.
    #[arg(long, value_enum, default_value_t = AttributionFormatArg::Text)]
    pub format: AttributionFormatArg,
}

/// Print the embedded third-party attribution document to stdout and
/// exit 0.
pub fn run(args: &AttributionArgs) -> ExitCode {
    print!(
        "{}",
        hort_attribution::render_attribution(args.format.into())
    );
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_format_is_default_and_succeeds() {
        let code = run(&AttributionArgs {
            format: AttributionFormatArg::Text,
        });
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }

    #[test]
    fn json_format_differs_from_text_and_succeeds() {
        let text = hort_attribution::render_attribution(AttributionFormat::Text);
        let json = hort_attribution::render_attribution(AttributionFormat::Json);
        assert_ne!(text, json);
        let code = run(&AttributionArgs {
            format: AttributionFormatArg::Json,
        });
        assert_eq!(format!("{code:?}"), format!("{:?}", ExitCode::SUCCESS));
    }

    #[test]
    fn attribution_args_parses_default_and_json() {
        use clap::Parser;

        #[derive(Debug, Parser)]
        struct TestCli {
            #[command(subcommand)]
            command: super::super::Command,
        }

        let cli = TestCli::try_parse_from(["hort-server", "attribution"]).unwrap();
        let super::super::Command::Attribution(args) = cli.command else {
            panic!("expected Attribution");
        };
        assert_eq!(args.format, AttributionFormatArg::Text);

        let cli =
            TestCli::try_parse_from(["hort-server", "attribution", "--format", "json"]).unwrap();
        let super::super::Command::Attribution(args) = cli.command else {
            panic!("expected Attribution");
        };
        assert_eq!(args.format, AttributionFormatArg::Json);
    }
}
